### ARMADO DEL DATASET

In [1]:
import pandas as pd
import numpy as np
import scipy as sp
import glob

%matplotlib inline

INDICADORES

In [2]:
data = pd.read_excel(r'C:\Users\Erika\Desktop\PYTHON\input\MATRIZ\Indicadores Matriz de Riesgo.xlsx')

In [3]:
data.head()

,Segmento,Cod Cia,DenominacionCorta,periodo,ind_01,num_Ind_01,den_Ind_01,ind_02,num_Ind_02,den_Ind_02,...,den_Ind_40,ind_41,num_Ind_41,den_Ind_41,ind_42,num_Ind_42,den_Ind_42,ind_43,num_Ind_43,den_Ind_43
0,Personas_s/RM,822,INSTITUTO DE JUJUY,2012-2,-0,0.0,3.0,-0,0.0,3.0,...,0.0,"387,69097668131125380196012166",5735888,14795,"15085,8958333333",724123.0,48.0,"15085,8958333333",724123.0,48.0
1,Patrimoniales_Mixtas,823,IÚNIGO,2012-2,-0,0.0,3665705.0,-0,0.0,3665705.0,...,0.0,"74,16577861587392932931184199",14434218,194621,"0,672766652474309",3288219.0,4887607.0,"0,672766652474309",3288219.0,4887607.0
2,Automotores,2,SMG,2012-3,"0,146802925879989",41770748.0,284536209.0,"0,139001427483297",8058769.0,57976160.0,...,NaN,"0,5918434595360580881707175794",33452221,56522076,"0,421782094960691",54141183.0,128362924.0,"0,47388384323878",46894994.0,98958837.0
3,Personas_s/RM,6,SURCO,2012-3,"5,28517543245643E-02",1023863.0,19372356.0,NaN,NaN,5284657.0,...,NaN,"318,61462722769224444490123127",31000566,97298,"0,372488110469793",9516993.0,25549790.0,"0,376081738996534",9510393.0,25288101.0
4,Patrimoniales_Mixtas,7,CAMINOS PROTEGIDOS,2012-3,-0,0.0,6515693.0,-0,0.0,2733053.0,...,0.0,"78,684587253461694745725627481",27690916,351923,"0,161439910008841",627453.0,3886604.0,"0,166781140703654",627453.0,3762134.0

In [4]:
data.columns

Index(['Segmento', 'Cod Cia', 'DenominacionCorta', 'periodo', 'ind_01',
       'num_Ind_01', 'den_Ind_01', 'ind_02', 'num_Ind_02', 'den_Ind_02',
       ...
       'den_Ind_40', 'ind_41', 'num_Ind_41', 'den_Ind_41', 'ind_42',
       'num_Ind_42', 'den_Ind_42', 'ind_43', 'num_Ind_43', 'den_Ind_43'],
      dtype='object', length=130)

In [5]:
#Filtro las columnas

colum = ['Segmento', 'Cod Cia', 'DenominacionCorta', 'periodo','ind_01','ind_02','ind_03','ind_04','ind_05','ind_06','ind_08','ind_09','ind_10','ind_11','ind_12',
'ind_13','ind_14','ind_15','ind_16','ind_17','ind_18','ind_19','ind_20','ind_21','ind_22','ind_23','ind_24','ind_25',
'ind_26','ind_27','ind_28','ind_29','ind_30','ind_31','ind_32','ind_33','ind_34','ind_35','ind_36','ind_37','ind_38',
'ind_39','ind_40','ind_41','ind_42','ind_43']

data = data[colum]

In [6]:
# Reemplazo NA
data = data.fillna(0)

# Remplazo los "den_cero"
data = data.replace(to_replace='den_cero', value=0)

In [7]:
# Me quedo a parte con la columna de compañias
encabezado = data[['Segmento','Cod Cia', 'DenominacionCorta','periodo']]

# Filtro todo lo que no sea indicadores
col_num= ['Cod Cia','ind_01','ind_02','ind_03','ind_04','ind_05','ind_06','ind_08','ind_09','ind_10','ind_11','ind_12',
'ind_13','ind_14','ind_15','ind_16','ind_17','ind_18','ind_19','ind_20','ind_21','ind_22','ind_23','ind_24','ind_25',
'ind_26','ind_27','ind_28','ind_29','ind_30','ind_31','ind_32','ind_33','ind_34','ind_35','ind_36','ind_37','ind_38',
'ind_39','ind_40','ind_41','ind_42','ind_43']

indicadores= data[col_num]

In [8]:
# Reemplazo punto por coma y lo convierto en flotante

for i in indicadores.columns:
    indicadores[i] = indicadores[i].map(lambda x: x if isinstance(x,int) else float(x.replace(",",".")))

C:\Users\Erika\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [9]:
indicadores.head()

,Cod Cia,ind_01,ind_02,ind_03,ind_04,ind_05,ind_06,ind_08,ind_09,ind_10,...,ind_34,ind_35,ind_36,ind_37,ind_38,ind_39,ind_40,ind_41,ind_42,ind_43
0,822,-0.000000,-0.000000,0.000000,0.000009,0.000000,1.000000,1.000000,0.000000,0.000000,...,15085.895833,0.000000,-0.000000,15085.958333,0.062500,0.062500,0.0,387.690977,15085.895833,15085.895833
1,823,-0.000000,-0.000000,0.000000,0.013008,-0.001586,0.935879,0.708833,0.000000,0.000000,...,0.512960,0.101444,-0.000000,1.422767,0.750000,0.750000,0.0,74.165779,0.672767,0.672767
2,2,0.146803,0.139001,0.032215,0.361734,-0.014188,0.804980,0.000000,0.672356,0.000000,...,0.149917,0.279136,0.193382,1.128130,0.654247,0.715473,0.0,0.591843,0.421782,0.473884
3,6,0.052852,0.000000,0.000000,0.294465,-0.018312,0.505895,0.000000,0.000000,0.023392,...,0.350829,0.047854,0.008975,0.732065,0.355984,0.366381,0.0,318.614627,0.372488,0.376082
4,7,-0.000000,-0.000000,0.000000,0.061645,-0.093294,0.158777,0.456818,0.834198,0.000443,...,0.176108,0.003491,0.142511,0.317634,0.150852,0.146021,0.0,78.684587,0.161440,0.166781

In [10]:
# Junto Dataset

dt_indicadores = encabezado.merge(indicadores, on='Cod Cia', left_index=True, right_index=True)

#dt_indicadores= pd.concat([encabezado, indicadores])

In [11]:
dt_indicadores = dt_indicadores.rename(columns = {'Cod Cia':'cod_cia'})

In [12]:
dt_indicadores.head(20)

,Segmento,cod_cia,DenominacionCorta,periodo,ind_01,ind_02,ind_03,ind_04,ind_05,ind_06,...,ind_34,ind_35,ind_36,ind_37,ind_38,ind_39,ind_40,ind_41,ind_42,ind_43
0,Personas_s/RM,822,INSTITUTO DE JUJUY,2012-2,-0.000000,-0.000000,0.000000,0.000009,0.000000,1.000000,...,15085.895833,0.000000,-0.000000,15085.958333,0.062500,0.062500,0.000000,387.690977,15085.895833,15085.895833
1,Patrimoniales_Mixtas,823,IÚNIGO,2012-2,-0.000000,-0.000000,0.000000,0.013008,-0.001586,0.935879,...,0.512960,0.101444,-0.000000,1.422767,0.750000,0.750000,0.000000,74.165779,0.672767,0.672767
2,Automotores,2,SMG,2012-3,0.146803,0.139001,0.032215,0.361734,-0.014188,0.804980,...,0.149917,0.279136,0.193382,1.128130,0.654247,0.715473,0.000000,0.591843,0.421782,0.473884
3,Personas_s/RM,6,SURCO,2012-3,0.052852,0.000000,0.000000,0.294465,-0.018312,0.505895,...,0.350829,0.047854,0.008975,0.732065,0.355984,0.366381,0.000000,318.614627,0.372488,0.376082
4,Patrimoniales_Mixtas,7,CAMINOS PROTEGIDOS,2012-3,-0.000000,-0.000000,0.000000,0.061645,-0.093294,0.158777,...,0.176108,0.003491,0.142511,0.317634,0.150852,0.146021,0.000000,78.684587,0.161440,0.166781
5,Patrimoniales_Mixtas,11,COMERCIO,2012-3,0.095164,0.034995,0.017782,0.299452,-0.017999,0.832940,...,0.145215,0.299170,0.071035,1.240534,0.743512,0.734548,0.000000,21.704942,0.469354,0.497022
6,Automotores,25,SURA,2012-3,0.169161,0.023642,0.049949,0.426382,-0.014267,0.868305,...,0.203650,0.204828,0.106757,0.992870,0.515578,0.509842,0.000000,10.852803,0.454467,0.477293
7,Automotores,32,BOSTON,2012-3,0.598821,0.120864,0.167596,0.560279,-0.021333,0.709601,...,0.202446,0.206838,0.300986,1.063682,0.576307,0.507125,0.000000,1.788726,0.366989,0.487375
8,Automotores,36,ALLIANZ,2012-3,0.456476,0.343485,0.074563,0.377228,-0.033411,0.660797,...,0.158920,0.224556,0.314846,1.055639,0.560171,0.469580,0.011075,0.647965,0.419682,0.495468
9,Automotores,39,ZURICH ASEGURADORA,2012-3,0.175903,0.079151,0.146605,0.323177,-0.021645,0.668201,...,0.133935,0.300690,0.123949,1.034134,0.524101,0.557524,0.000000,7.553690,0.461257,0.510034
10,Patrimoniales_Mixtas,40,PRUDENCIA,2012-3,0.128104,0.000000,0.075984,0.271879,-0.076569,0.828749,...,0.312347,0.331280,0.117814,0.975194,0.275552,0.249764,0.000000,10.678437,0.643494,0.699642
11,Automotores,44,EQUITATIVA DEL PLATA,2012-3,0.087759,0.000000,0.065552,0.323432,-0.012541,0.808820,...,0.317745,0.187429,0.166563,1.079230,0.511331,0.375605,0.000000,13.235442,0.514400,0.567899
12,Automotores,57,CALEDONIA,2012-3,-0.000000,0.000000,0.000000,0.447147,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
13,Automotores,64,VICTORIA,2012-3,0.223262,0.199377,0.044111,0.346317,-0.105928,0.611284,...,0.271557,0.185737,0.158102,1.056940,0.514725,0.401500,0.000000,11.100087,0.517786,0.542215
14,Patrimoniales_Mixtas,71,XL INSURANCE,2012-3,0.894441,0.000000,0.161308,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,Automotores,116,MERCANTIL ANDINA,2012-3,0.060868,0.028826,0.025464,0.255229,-0.022627,0.781308,...,0.212688,0.243380,0.029011,1.069483,0.564296,0.547739,0.000000,31.849462,0.497598,0.505187
16,Personas_s/RM,117,SEGUNDA PERSONAS,2012-3,0.118492,-0.000000,0.009107,0.278460,-0.013048,0.913469,...,0.230796,0.198888,0.025489,0.973576,0.398987,0.424783,0.001291,0.000000,0.528674,0.574590
17,Automotores,121,BERKLEY,2012-3,0.123280,0.255847,0.090330,0.225918,-0.035923,0.761378,...,0.123526,0.285952,0.205277,1.103666,0.628836,0.561937,-0.000746,22.405844,0.430978,0.474830
18,Personas_s/RM,136,MERCANTIL ASEGURADORA,2012-3,0.000000,0.000000,0.186478,0.000000,0.000000,0.000000,...,0.580972,0.050458,0.000000,0.000000,0.128343,0.128343,0.000000,0.000000,0.657889,0.000000
19,Automotores,141,NORTE,2012-3,0.022617,-0.000000,0.000000,0.149802,-0.009572,0.832761,...,0.261667,0.242165,0.049652,0.910214,0.357274,0.346698,0.000000,26.216382,0.544897,0.552940

BALANCES y ECM

In [13]:
# Importe los bvalances ya agrupados

balances = pd.read_excel(r'C:\Users\Erika\Desktop\PYTHON\output\Balance\df_new.xlsx')

In [14]:
balances.head()

,cod_cia,Segmento,periodo,DenominacionCorta,CM_requerido,Ccomputable,juicios,Deficit,solv_1,solv_2,...,5.02.04.04.04.50.00.00,5.03.00.00.00.00.00.00,Segmento_ART,Segmento_Automotores,Segmento_Créditos/Caución,Segmento_Patrimoniales_Mixtas,Segmento_Personas_s/RM,Segmento_Retiro,Segmento_TPP,Segmento_Vida_RM
0,2,Automotores,2012-2,SMG,4.497781e+07,157205955,1897,0,8.593679e+07,8.677640e+07,...,32057.0,0.0,0,1,0,0,0,0,0,0
1,2,Automotores,2012-3,SMG,5.161174e+07,137548535,1893,0,8.677640e+07,1.128246e+08,...,153432.0,0.0,0,1,0,0,0,0,0,0
2,2,Automotores,2012-4,SMG,5.629319e+07,143069589,1748,0,1.128246e+08,8.678744e+07,...,84449.0,0.0,0,1,0,0,0,0,0,0
3,2,Automotores,2013-1,SMG,6.089003e+07,173714678,1736,0,8.678744e+07,1.053025e+08,...,32464.0,0.0,0,1,0,0,0,0,0,0
4,2,Automotores,2013-2,SMG,6.730049e+07,154087933,1827,0,1.053025e+08,1.098144e+08,...,34666.0,0.0,0,1,0,0,0,0,0,0

In [15]:
balances=balances.drop({'Segmento','DenominacionCorta'},1)

In [16]:
Dataset_final=balances.merge(dt_indicadores, how='inner', on=['cod_cia','periodo'])

In [17]:
Dataset_final.head()

,cod_cia,periodo,CM_requerido,Ccomputable,juicios,Deficit,solv_1,solv_2,solv_3,solv_4,...,ind_34,ind_35,ind_36,ind_37,ind_38,ind_39,ind_40,ind_41,ind_42,ind_43
0,2,2012-2,4.497781e+07,157205955,1897,0,8.593679e+07,8.677640e+07,1.128246e+08,8.678744e+07,...,0.138154,0.249423,0.234651,1.052427,0.594813,0.595088,0.0,0.624252,0.407543,0.457614
1,2,2012-3,5.161174e+07,137548535,1893,0,8.677640e+07,1.128246e+08,8.678744e+07,1.053025e+08,...,0.149917,0.279136,0.193382,1.128130,0.654247,0.715473,0.0,0.591843,0.421782,0.473884
2,2,2012-4,5.629319e+07,143069589,1748,0,1.128246e+08,8.678744e+07,1.053025e+08,1.098144e+08,...,0.140151,0.270848,0.222298,1.114193,0.642695,0.780216,0.0,0.961507,0.417951,0.471498
3,2,2013-1,6.089003e+07,173714678,1736,0,8.678744e+07,1.053025e+08,1.098144e+08,1.487009e+08,...,0.137632,0.270922,0.229954,1.056411,0.595577,0.670160,0.0,0.536766,0.421371,0.460834
4,2,2013-2,6.730049e+07,154087933,1827,0,1.053025e+08,1.098144e+08,1.487009e+08,2.135388e+08,...,0.129823,0.257266,0.254726,1.078777,0.620567,0.684190,0.0,0.502794,0.414008,0.458209

In [18]:
#cambiar= pd.DataFrame(Dataset_final.columns.values.tolist())

In [19]:
cambiar= pd.read_excel(r'C:\Users\Erika\Desktop\PYTHON\output\Balance\cambiar1.xlsx')

In [20]:
#cambiar.to_excel(r'C:\Users\Erika\Desktop\PYTHON\output\Balance\cambiar1.xlsx', index=False)

In [21]:
Dataset_final = Dataset_final[cambiar.columns]

In [22]:
Dataset_final.head()

,cod_cia,periodo,Segmento,DenominacionCorta,1.00.00.00.00.00.00.00,1.01.00.00.00.00.00.00,1.01.01.00.00.00.00.00,1.01.01.01.00.00.00.00,1.01.01.01.01.00.00.00,1.01.01.01.01.01.00.00,...,ind_36,ind_37,ind_38,ind_39,ind_40,ind_41,ind_42,ind_43,Deficit,target
0,2,2012-2,Automotores,SMG,566593246.0,11885274.0,3250465.0,3250465.0,3250465.0,278167.0,...,0.234651,1.052427,0.594813,0.595088,0.0,0.624252,0.407543,0.457614,0,0
1,2,2012-3,Automotores,SMG,586676265.0,11918947.0,3233892.0,3233892.0,3233892.0,177962.0,...,0.193382,1.128130,0.654247,0.715473,0.0,0.591843,0.421782,0.473884,0,0
2,2,2012-4,Automotores,SMG,625268985.0,11902870.0,2818391.0,2818391.0,2818391.0,130288.0,...,0.222298,1.114193,0.642695,0.780216,0.0,0.961507,0.417951,0.471498,0,0
3,2,2013-1,Automotores,SMG,674591662.0,7110632.0,6717952.0,6717952.0,6717952.0,171122.0,...,0.229954,1.056411,0.595577,0.670160,0.0,0.536766,0.421371,0.460834,0,0
4,2,2013-2,Automotores,SMG,740195439.0,19484948.0,2838685.0,2838685.0,2838685.0,134419.0,...,0.254726,1.078777,0.620567,0.684190,0.0,0.502794,0.414008,0.458209,0,0

In [23]:
# Exporto

Dataset_final.to_csv(r'C:\Users\Erika\Desktop\PYTHON\output\Balance\dt_trabajo_1.csv', index=False, encoding='utf-8')

In [26]:
evaluar = Dataset_final[Dataset_final['periodo']=='2019-2']

In [27]:
evaluar[evaluar['Deficit']==1]

,cod_cia,periodo,Segmento,DenominacionCorta,1.00.00.00.00.00.00.00,1.01.00.00.00.00.00.00,1.01.01.00.00.00.00.00,1.01.01.01.00.00.00.00,1.01.01.01.01.00.00.00,1.01.01.01.01.01.00.00,...,ind_36,ind_37,ind_38,ind_39,ind_40,ind_41,ind_42,ind_43,Deficit,target
291,57,2019-2,Automotores,CALEDONIA,5.816620e+08,33687807.0,2818538.0,2818538.0,2818538.0,0.0,...,-0.000000,1.014700,0.444753,0.412252,0.0,432.320215,0.562154,0.569947,1,0
2267,433,2019-2,Retiro,EXPERTA RETIRO,3.676040e+07,755429.0,0.0,0.0,0.0,0.0,...,0.000000,-0.130298,0.000000,0.000000,0.0,317.490801,-0.130298,-0.130298,1,0
2956,553,2019-2,Personas_s/RM,CRUZ SUIZA,4.050269e+07,4550635.0,20000.0,20000.0,20000.0,0.0,...,0.157809,0.877024,0.167314,0.188354,0.0,0.000000,0.623073,0.709710,1,0
3521,621,2019-2,ART,PROVINCIA ART,3.362107e+10,40748231.0,11204954.0,11204954.0,11204954.0,0.0,...,0.000781,1.344308,1.172757,1.171856,0.0,8.374815,0.171419,0.171551,1,0
4914,845,2019-2,Personas_s/RM,NSA,7.251716e+06,7023.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,1,0
4925,847,2019-2,Personas_s/RM,SAN GERMAN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.012691,0.000000,0.051082,0.050295,0.0,19.826022,1.416860,0.000000,1,0